DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS alerts;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deviceId INTEGER UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    avg FLOAT NOT NULL,
    max FLOAT NOT NULL,
    time TIMESTAMP,
    lat FLOAT NOT NULL,
    lng FLOAT NOT NULL
)